// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGw9vNshNVhfiKi56GZvHAgCRcI1zpkrg',
    appId: '1:536542631640:web:1c84242022ccd57a1ae9ad',
    messagingSenderId: '536542631640',
    projectId: 'wahab-baea1',
    authDomain: 'wahab-baea1.firebaseapp.com',
    storageBucket: 'wahab-baea1.firebasestorage.app',
    measurementId: 'G-0PES78CHPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_GVmGhplBcTfgg8L_6XeG_Dm5A-cmDs',
    appId: '1:536542631640:android:6d352ad8eef21af91ae9ad',
    messagingSenderId: '536542631640',
    projectId: 'wahab-baea1',
    storageBucket: 'wahab-baea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1TJtXTGBXVVy5zM1JELnh8bZNLgbSJQ',
    appId: '1:536542631640:ios:ba23d3ef4448fe0a1ae9ad',
    messagingSenderId: '536542631640',
    projectId: 'wahab-baea1',
    storageBucket: 'wahab-baea1.firebasestorage.app',
    iosBundleId: 'com.example.wahab',
  );

}