// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/events/model/event_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2006261101140995514),
    name: 'EventModel',
    lastPropertyId: const obx_int.IdUid(10, 358585546820936239),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 835777748264011980),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3295764467579825014),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7364585886307205691),
        name: 'desc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7247623852929078737),
        name: 'imagePaths',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7542844984979312469),
        name: 'tools',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 489287270241432582),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1385311369094534048),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2921592406769504122),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 358585546820936239),
        name: 'status',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2006261101140995514),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [5643504947583391236],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EventModel: obx_int.EntityDefinition<EventModel>(
      model: _entities[0],
      toOneRelations: (EventModel object) => [],
      toManyRelations: (EventModel object) => {},
      getId: (EventModel object) => object.id,
      setId: (EventModel object, int id) {
        object.id = id;
      },
      objectToFB: (EventModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descOffset = fbb.writeString(object.desc);
        final imagePathsOffset = fbb.writeList(
          object.imagePaths.map(fbb.writeString).toList(growable: false),
        );
        final toolsOffset = fbb.writeList(
          object.tools.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(3, descOffset);
        fbb.addOffset(4, imagePathsOffset);
        fbb.addOffset(5, toolsOffset);
        fbb.addInt64(6, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.type);
        fbb.addInt64(9, object.status);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final descParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final toolsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final imagePathsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = EventModel(
          id: idParam,
          title: titleParam,
          type: typeParam,
          desc: descParam,
          status: statusParam,
          tools: toolsParam,
          imagePaths: imagePathsParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EventModel] entity fields to define ObjectBox queries.
class EventModel_ {
  /// See [EventModel.id].
  static final id = obx.QueryIntegerProperty<EventModel>(
    _entities[0].properties[0],
  );

  /// See [EventModel.title].
  static final title = obx.QueryStringProperty<EventModel>(
    _entities[0].properties[1],
  );

  /// See [EventModel.desc].
  static final desc = obx.QueryStringProperty<EventModel>(
    _entities[0].properties[2],
  );

  /// See [EventModel.imagePaths].
  static final imagePaths = obx.QueryStringVectorProperty<EventModel>(
    _entities[0].properties[3],
  );

  /// See [EventModel.tools].
  static final tools = obx.QueryStringVectorProperty<EventModel>(
    _entities[0].properties[4],
  );

  /// See [EventModel.createdAt].
  static final createdAt = obx.QueryDateProperty<EventModel>(
    _entities[0].properties[5],
  );

  /// See [EventModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<EventModel>(
    _entities[0].properties[6],
  );

  /// See [EventModel.type].
  static final type = obx.QueryIntegerProperty<EventModel>(
    _entities[0].properties[7],
  );

  /// See [EventModel.status].
  static final status = obx.QueryIntegerProperty<EventModel>(
    _entities[0].properties[8],
  );
}
