// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox/product_entity.dart';
import 'objectbox/product_image_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6393634065084584965),
    name: 'ProductEntity',
    lastPropertyId: const obx_int.IdUid(22, 1132662813978316544),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2300918573255082728),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5940906248992659699),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8269862436780686006),
        name: 'group',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1383092311999833631),
        name: 'tools',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3856719868647136951),
        name: 'imagePaths',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4608265219138738634),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5007054384082180739),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 755765851379316266),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5056162910351239549),
        name: 'toolsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8342622635637120733),
        name: 'imagePathsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1455209405643878324),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 991441405569826948),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 1132662813978316544),
        name: 'isDirty',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 3825000397718416616),
        name: 'images',
        targetId: const obx_int.IdUid(2, 6798172890663994946),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6798172890663994946),
    name: 'ProductImageEntity',
    lastPropertyId: const obx_int.IdUid(3, 8541179439823808234),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 241555931658171020),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 733794576294248886),
        name: 'key',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4482858388215303397),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8541179439823808234),
        name: 'bytes',
        type: 23,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6798172890663994946),
    lastIndexId: const obx_int.IdUid(8, 991441405569826948),
    lastRelationId: const obx_int.IdUid(4, 3825000397718416616),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [
      2002207992160916427,
      8679784319883672849,
      7474941581539515418,
      8964885818835525835,
      3581919160989929613,
      6886728735377376614,
    ],
    retiredPropertyUids: const [
      8802302739639446131,
      5964231682117815840,
      1140867336874532647,
      4042665561352495720,
      5169526714075081934,
      7797874375361365240,
      1467947136272157926,
      7062926609661586230,
      68554073085096292,
      6491563542059344784,
    ],
    retiredRelationUids: const [
      2199856507267009753,
      3944794487697887128,
      1416576572525953888,
    ],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductEntity: obx_int.EntityDefinition<ProductEntity>(
      model: _entities[0],
      toOneRelations: (ProductEntity object) => [],
      toManyRelations: (ProductEntity object) => {
        obx_int.RelInfo<ProductEntity>.toMany(4, object.obId): object.images,
      },
      getId: (ProductEntity object) => object.obId,
      setId: (ProductEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (ProductEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final groupOffset = fbb.writeString(object.group);
        final toolsOffset = fbb.writeList(
          object.tools.map(fbb.writeString).toList(growable: false),
        );
        final imagePathsOffset = fbb.writeList(
          object.imagePaths.map(fbb.writeString).toList(growable: false),
        );
        final descriptionOffset = fbb.writeString(object.description);
        final toolsJsonOffset = fbb.writeString(object.toolsJson);
        final imagePathsJsonOffset = fbb.writeString(object.imagePathsJson);
        final idOffset = fbb.writeString(object.id);
        fbb.startTable(23);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, groupOffset);
        fbb.addOffset(5, toolsOffset);
        fbb.addOffset(6, imagePathsOffset);
        fbb.addInt64(7, object.createdAtMs);
        fbb.addInt64(8, object.updatedAtMs);
        fbb.addOffset(11, descriptionOffset);
        fbb.addOffset(12, toolsJsonOffset);
        fbb.addOffset(13, imagePathsJsonOffset);
        fbb.addOffset(20, idOffset);
        fbb.addBool(21, object.isDirty);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final groupParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final toolsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final imagePathsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final createdAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final isDirtyParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          46,
          false,
        );
        final object =
            ProductEntity(
                obId: obIdParam,
                id: idParam,
                title: titleParam,
                group: groupParam,
                description: descriptionParam,
                toolsJson: toolsJsonParam,
                imagePathsJson: imagePathsJsonParam,
                createdAtMs: createdAtMsParam,
                updatedAtMs: updatedAtMsParam,
                isDirty: isDirtyParam,
              )
              ..tools = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 14, [])
              ..imagePaths = const fb.ListReader<String>(
                fb.StringReader(asciiOptimization: true),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 16, []);
        obx_int.InternalToManyAccess.setRelInfo<ProductEntity>(
          object.images,
          store,
          obx_int.RelInfo<ProductEntity>.toMany(4, object.obId),
        );
        return object;
      },
    ),
    ProductImageEntity: obx_int.EntityDefinition<ProductImageEntity>(
      model: _entities[1],
      toOneRelations: (ProductImageEntity object) => [],
      toManyRelations: (ProductImageEntity object) => {},
      getId: (ProductImageEntity object) => object.obId,
      setId: (ProductImageEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (ProductImageEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final bytesOffset = fbb.writeListInt8(object.bytes);
        fbb.startTable(4);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, bytesOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bytesParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGet(buffer, rootOffset, 8, Uint8List(0))
                as Uint8List;
        final object = ProductImageEntity(
          obId: obIdParam,
          key: keyParam,
          bytes: bytesParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductEntity] entity fields to define ObjectBox queries.
class ProductEntity_ {
  /// See [ProductEntity.obId].
  static final obId = obx.QueryIntegerProperty<ProductEntity>(
    _entities[0].properties[0],
  );

  /// See [ProductEntity.title].
  static final title = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[1],
  );

  /// See [ProductEntity.group].
  static final group = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[2],
  );

  /// See [ProductEntity.tools].
  static final tools = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[0].properties[3],
  );

  /// See [ProductEntity.imagePaths].
  static final imagePaths = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[0].properties[4],
  );

  /// See [ProductEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ProductEntity>(
    _entities[0].properties[5],
  );

  /// See [ProductEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<ProductEntity>(
    _entities[0].properties[6],
  );

  /// See [ProductEntity.description].
  static final description = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[7],
  );

  /// See [ProductEntity.toolsJson].
  static final toolsJson = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[8],
  );

  /// See [ProductEntity.imagePathsJson].
  static final imagePathsJson = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[9],
  );

  /// See [ProductEntity.id].
  static final id = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[10],
  );

  /// See [ProductEntity.isDirty].
  static final isDirty = obx.QueryBooleanProperty<ProductEntity>(
    _entities[0].properties[11],
  );

  /// see [ProductEntity.images]
  static final images =
      obx.QueryRelationToMany<ProductEntity, ProductImageEntity>(
        _entities[0].relations[0],
      );
}

/// [ProductImageEntity] entity fields to define ObjectBox queries.
class ProductImageEntity_ {
  /// See [ProductImageEntity.obId].
  static final obId = obx.QueryIntegerProperty<ProductImageEntity>(
    _entities[1].properties[0],
  );

  /// See [ProductImageEntity.key].
  static final key = obx.QueryStringProperty<ProductImageEntity>(
    _entities[1].properties[1],
  );

  /// See [ProductImageEntity.bytes].
  static final bytes = obx.QueryByteVectorProperty<ProductImageEntity>(
    _entities[1].properties[2],
  );
}
