// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox/product_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6325593865609052828),
    name: 'ProductEntity',
    lastPropertyId: const obx_int.IdUid(7, 3844230579915402002),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8591119453577104809),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4022932719659542640),
        name: 'firebaseId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6100498532185635186),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7407146759109476084),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3912098203805717944),
        name: 'group',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6699404146537645459),
        name: 'desc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8190242792405447417),
        name: 'tool',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3844230579915402002),
        name: 'imageURL',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6325593865609052828),
    lastIndexId: const obx_int.IdUid(1, 6100498532185635186),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductEntity: obx_int.EntityDefinition<ProductEntity>(
      model: _entities[0],
      toOneRelations: (ProductEntity object) => [],
      toManyRelations: (ProductEntity object) => {},
      getId: (ProductEntity object) => object.obId,
      setId: (ProductEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (ProductEntity object, fb.Builder fbb) {
        final firebaseIdOffset = fbb.writeString(object.firebaseId);
        final titleOffset = fbb.writeString(object.title);
        final groupOffset = fbb.writeString(object.group);
        final descOffset = fbb.writeString(object.desc);
        final toolOffset = fbb.writeList(
          object.tool.map(fbb.writeString).toList(growable: false),
        );
        final imageURLOffset = fbb.writeList(
          object.imageURL.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, firebaseIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, groupOffset);
        fbb.addOffset(4, descOffset);
        fbb.addOffset(5, toolOffset);
        fbb.addOffset(6, imageURLOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firebaseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final groupParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final toolParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final imageURLParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 16, []);
        final object = ProductEntity(
          obId: obIdParam,
          firebaseId: firebaseIdParam,
          title: titleParam,
          group: groupParam,
          desc: descParam,
          tool: toolParam,
          imageURL: imageURLParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductEntity] entity fields to define ObjectBox queries.
class ProductEntity_ {
  /// See [ProductEntity.obId].
  static final obId = obx.QueryIntegerProperty<ProductEntity>(
    _entities[0].properties[0],
  );

  /// See [ProductEntity.firebaseId].
  static final firebaseId = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[1],
  );

  /// See [ProductEntity.title].
  static final title = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[2],
  );

  /// See [ProductEntity.group].
  static final group = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[3],
  );

  /// See [ProductEntity.desc].
  static final desc = obx.QueryStringProperty<ProductEntity>(
    _entities[0].properties[4],
  );

  /// See [ProductEntity.tool].
  static final tool = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[0].properties[5],
  );

  /// See [ProductEntity.imageURL].
  static final imageURL = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[0].properties[6],
  );
}
